### ISSUE TITLE
MobileViT model loading issues

### ISSUE THREAD

**Issue by veb-101** [james77777778/keras-image-models#45]
There's an issue loading MobileViT with image sizes whose `output_stride` is not divisible by 2. The model works well with input_shape `(256, 256, 3)` but not with `(None, None, 3)` or `(224, 224, 3)`. 

```python
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 7, 7, 80), (None, 8, 8, 80)]
```

I faced the same issue. It seems like the resize method used in the original repo is really needed. 

For resolving the `(None, None, 3)` inputs I had to write overwrite the [compute_output_shape(...)](https://github.com/veb-101/keras-vision/blob/d26b0eb43cc6f982570601312b5bc7db931811d3/keras_vision/MobileViT_v1/mobile_vit_v1_block.py#L132) method. 

However, this led to another issue where the layer parameters weren't being initialized. To resolve this, I had to pass a dummy data ([like this](https://github.com/veb-101/keras-vision/blob/d26b0eb43cc6f982570601312b5bc7db931811d3/keras_vision/MobileViT_v1/mobile_vit_v1.py#L209)) before returning the model. 

This is not a dig at your repository. I am sharing that I faced the issues and the solutions to fix them since you and I are working toward the same goal.

**Comment by james77777778** [comment]
Hi @veb-101 

Thanks for reporting this issue.
I believe it is related to some transformer-based models and might be solvable by interpolating the feature map or the weights.

I will look into this and report back.

**Comment by james77777778** [comment]
I have fixed it and pushed a new release for this.
You can refer to https://github.com/james77777778/keras-image-models/releases/tag/0.2.1 and install it by
`pip install -U kimm`

The details:
- `MobileViT*`: Add `keras.ops.resize` to the feature map
- `VisionTrasformer*`: Add mechanism to interpolate the weights of `PosisionEmbedding` during loading

I'm closing this issue.
Feel free to reopen it if it is not resolved.
